// Auto-generated by scripts/update-toolify-data.mjs
export const toolifyData = {
  "updatedAt": "2026-05-16T12:02:04.472Z",
  "source": "Toolify public ranking pages via r.jina.ai with curated fallback when blocked",
  "sections": [
    {
      "key": "top-tools",
      "title": "Top validated AI tools",
      "subtitle": "10 AI products ranking near the front of Toolify-style market lists.",
      "kind": "products",
      "items": [
        {
          "name": "Claude 2",
          "toolifyUrl": "https://www.toolify.ai/tool/claude-2",
          "website": "",
          "visits": "823.5M",
          "description": "AI assistant, Natural language processing, Task automation, API access, Web access",
          "icon": "https://icons.duckduckgo.com/ip3/claude.ai.ico",
          "rank": 1
        },
        {
          "name": "Gemini & Gemini Advanced",
          "toolifyUrl": "https://www.toolify.ai/tool/gemini-gemini-advanced",
          "website": "",
          "visits": "2.8B",
          "description": "AI assistant, Conversational AI, Google AI, Productivity tool, Writing assistant, Research tool, Content creation, Personal assistant",
          "icon": "https://icons.duckduckgo.com/ip3/gemini.google.com.ico",
          "rank": 2
        },
        {
          "name": "Deepseek",
          "toolifyUrl": "https://www.toolify.ai/tool/deepseek",
          "website": "",
          "visits": "411.2M",
          "description": "LLM, Large Language Model, AI, Artificial Intelligence, Deep Learning, Machine Learning, API, Code Generation, MoE, Open Source, Chatbot, Reasoning, Mathematics",
          "icon": "https://icons.duckduckgo.com/ip3/deepseek.com.ico",
          "rank": 3
        },
        {
          "name": "Magnific (formerly Freepik)",
          "toolifyUrl": "https://www.toolify.ai/tool/magnific-formerly-freepik",
          "website": "",
          "visits": "9.4M",
          "description": "AI Creative Platform, Video Upscaling, AI Video Generator, AI Image Generator, Node-based Workflow, Brand Consistency, Freepik, AI Storyboarding",
          "icon": "https://icons.duckduckgo.com/ip3/freepik.com.ico",
          "rank": 4
        },
        {
          "name": "Meshy",
          "toolifyUrl": "https://www.toolify.ai/tool/meshy",
          "website": "",
          "visits": "18.1M",
          "description": "3D, AI, Generative AI, 3D modeling, 3D printing, Game development, Text to 3D, Image to 3D, Text to texture, Image to texture, AR, VR, XR, Computer Vision, Machine Learning, Voxel,",
          "icon": "https://icons.duckduckgo.com/ip3/meshy.ai.ico",
          "rank": 5
        },
        {
          "name": "JanitorAI",
          "toolifyUrl": "https://www.toolify.ai/tool/janitorai",
          "website": "",
          "visits": "99.1M",
          "description": "NSFW chatbot, Fictional characters, AI character creation, Role-playing, Large language models",
          "icon": "https://icons.duckduckgo.com/ip3/janitorai.com.ico",
          "rank": 6
        },
        {
          "name": "SpicyChat AI",
          "toolifyUrl": "https://www.toolify.ai/tool/spicychat-ai",
          "website": "",
          "visits": "82.0M",
          "description": "AI chatbot, AI character, Chatbot platform, AI conversation, Chatbot creation, Community chatbots",
          "icon": "https://icons.duckduckgo.com/ip3/spicychat.ai.ico",
          "rank": 7
        },
        {
          "name": "PolyBuzz",
          "toolifyUrl": "https://www.toolify.ai/tool/polybuzz",
          "website": "",
          "visits": "55.0M",
          "description": "AI chatbot, AI character, Virtual character, AI companion, Avatar generator, Background image generator, Role-playing, Artificial intelligence, AI girlfriend, Anime AI",
          "icon": "https://icons.duckduckgo.com/ip3/polybuzz.ai.ico",
          "rank": 8
        },
        {
          "name": "Meta AI",
          "toolifyUrl": "https://www.toolify.ai/tool/meta-ai",
          "website": "",
          "visits": "23.1M",
          "description": "AI assistant, Large language model, Image generation, Voice conversation, Meta AI, Llama 4, Personal AI",
          "icon": "https://icons.duckduckgo.com/ip3/metaai.com.ico",
          "rank": 9
        },
        {
          "name": "Use AI",
          "toolifyUrl": "https://www.toolify.ai/tool/use-ai",
          "website": "",
          "visits": "25.6M",
          "description": "AI Chat Assistant, Multi-LLM, GPT-5, Claude, AI Models, Voice Command AI, Coding Assistant, Content Generation",
          "icon": "https://icons.duckduckgo.com/ip3/useai.com.ico",
          "rank": 10
        }
      ]
    },
    {
      "key": "high-traffic-categories",
      "title": "High-traffic categories",
      "subtitle": "10 categories with broad search and usage demand.",
      "kind": "categories",
      "items": [
        {
          "name": "AI Chatbot",
          "url": "https://www.toolify.ai/category/ai-chatbot",
          "description": "General assistant and role-play chat products with massive traffic.",
          "rank": 1
        },
        {
          "name": "AI Writing Assistants",
          "url": "https://www.toolify.ai/category/ai-writing-assistants",
          "description": "Writing, paraphrasing, grammar, and content production.",
          "rank": 2
        },
        {
          "name": "AI Image Generator",
          "url": "https://www.toolify.ai/category/ai-image-generator",
          "description": "Creative generation, avatars, ads, and product images.",
          "rank": 3
        },
        {
          "name": "AI Video Generator",
          "url": "https://www.toolify.ai/category/ai-video-generator",
          "description": "Short video, editing, captions, and repurposing.",
          "rank": 4
        },
        {
          "name": "AI Code Assistant",
          "url": "https://www.toolify.ai/category/ai-code-assistant",
          "description": "Developer productivity, agents, debugging, and app generation.",
          "rank": 5
        },
        {
          "name": "AI Search Engine",
          "url": "https://www.toolify.ai/category/ai-search-engine",
          "description": "Answer engines, research tools, and citation workflows.",
          "rank": 6
        },
        {
          "name": "AI Productivity Tools",
          "url": "https://www.toolify.ai/category/ai-productivity-tools",
          "description": "Meeting, docs, workflow, automation, and office productivity.",
          "rank": 7
        },
        {
          "name": "AI Education Assistant",
          "url": "https://www.toolify.ai/category/ai-education-assistant",
          "description": "Tutoring, homework, language learning, and study workflows.",
          "rank": 8
        },
        {
          "name": "AI Voice Assistants",
          "url": "https://www.toolify.ai/category/ai-voice-assistants",
          "description": "TTS, voice cloning, dubbing, and audio generation.",
          "rank": 9
        },
        {
          "name": "AI Marketing Tools",
          "url": "https://www.toolify.ai/category/ai-marketing-tools",
          "description": "SEO, ads, landing pages, social content, and sales copy.",
          "rank": 10
        }
      ]
    },
    {
      "key": "fast-growth-tools",
      "title": "Fast-growth / rising tools",
      "subtitle": "10 rising tool ideas and products worth watching.",
      "kind": "products",
      "items": [
        {
          "name": "GPT image 2 Prompt",
          "toolifyUrl": "https://www.toolify.ai/prompts/gpt-image-2",
          "website": "https://www.toolify.ai/prompts/gpt-image-2",
          "visits": "New",
          "description": "Prompt collection riding image-generation demand.",
          "icon": "https://icons.duckduckgo.com/ip3/gptimage2.com.ico",
          "rank": 1
        },
        {
          "name": "AI Humanizer",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Humanizer",
          "website": "https://www.toolify.ai/search/AI%20Humanizer",
          "visits": "Rising",
          "description": "Tools that rewrite AI text into more natural human tone.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20humanizer.com.ico",
          "rank": 2
        },
        {
          "name": "AI Detector",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Detector",
          "website": "https://www.toolify.ai/search/AI%20Detector",
          "visits": "Rising",
          "description": "Content authenticity and AI-detection utilities.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20detector.com.ico",
          "rank": 3
        },
        {
          "name": "AI Resume Builder",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Resume%20Builder",
          "website": "https://www.toolify.ai/search/AI%20Resume%20Builder",
          "visits": "Rising",
          "description": "Career tools for resumes, cover letters, and ATS optimization.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20resume20builder.com.ico",
          "rank": 4
        },
        {
          "name": "AI PPT Maker",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20PPT%20Maker",
          "website": "https://www.toolify.ai/search/AI%20PPT%20Maker",
          "visits": "Rising",
          "description": "Presentation generation tools for business and education.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20ppt20maker.com.ico",
          "rank": 5
        },
        {
          "name": "AI Headshot Generator",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Headshot%20Generator",
          "website": "https://www.toolify.ai/search/AI%20Headshot%20Generator",
          "visits": "Rising",
          "description": "Personal branding photo tools for LinkedIn and portfolios.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20headshot20generator.com.ico",
          "rank": 6
        },
        {
          "name": "AI Video Generator",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Video%20Generator",
          "website": "https://www.toolify.ai/search/AI%20Video%20Generator",
          "visits": "Rising",
          "description": "Text-to-video and social video automation products.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20video20generator.com.ico",
          "rank": 7
        },
        {
          "name": "AI Logo Generator",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Logo%20Generator",
          "website": "https://www.toolify.ai/search/AI%20Logo%20Generator",
          "visits": "Rising",
          "description": "Branding micro-tools with strong small-business intent.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20logo20generator.com.ico",
          "rank": 8
        },
        {
          "name": "AI Voice Generator",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Voice%20Generator",
          "website": "https://www.toolify.ai/search/AI%20Voice%20Generator",
          "visits": "Rising",
          "description": "Voiceover and dubbing tools for creators.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20voice20generator.com.ico",
          "rank": 9
        },
        {
          "name": "AI Coding Agent",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Coding%20Agent",
          "website": "https://www.toolify.ai/search/AI%20Coding%20Agent",
          "visits": "Rising",
          "description": "Developer automation tools for code generation and review.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20coding20agent.com.ico",
          "rank": 10
        }
      ]
    },
    {
      "key": "paid-products",
      "title": "Products with payment signals",
      "subtitle": "10 products with payment-platform or subscription evidence.",
      "kind": "products",
      "items": [
        {
          "name": "ChatGPT",
          "toolifyUrl": "https://www.toolify.ai/tool/chatgpt-4",
          "website": "https://chatgpt.com/?utm_source=toolify",
          "visits": "5.5B",
          "description": "A free-to-use AI system for conversations, insights, and task automation.",
          "icon": "https://icons.duckduckgo.com/ip3/chatgpt.com.ico",
          "rank": 1
        },
        {
          "name": "Claude",
          "toolifyUrl": "https://www.toolify.ai/tool/claude-2",
          "website": "https://claude.ai/?utm_source=toolify",
          "visits": "823.5M",
          "description": "Claude is an AI assistant from Anthropic that helps with tasks via natural language.",
          "icon": "https://icons.duckduckgo.com/ip3/claude.ai.ico",
          "rank": 2
        },
        {
          "name": "Adobe",
          "toolifyUrl": "https://www.toolify.ai/tool/adobe",
          "website": "https://adobe.com/?utm_source=toolify",
          "visits": "370.4M",
          "description": "Adobe provides creative, marketing, and document management solutions.",
          "icon": "https://icons.duckduckgo.com/ip3/adobe.com.ico",
          "rank": 3
        },
        {
          "name": "Notion",
          "toolifyUrl": "https://www.toolify.ai/tool/notion-ai",
          "website": "https://affiliate.notion.so/ffsd1156ei0l",
          "visits": "174.5M",
          "description": "All-in-one workspace for notes, docs, projects, and AI-powered productivity.",
          "icon": "https://icons.duckduckgo.com/ip3/affiliate.notion.so.ico",
          "rank": 4
        },
        {
          "name": "Salesforce Platform",
          "toolifyUrl": "https://www.toolify.ai/tool/salesforce-einstein",
          "website": "https://force.com/?utm_source=toolify",
          "visits": "134.2M",
          "description": "A unified platform for data, AI, CRM, development, and security.",
          "icon": "https://icons.duckduckgo.com/ip3/force.com.ico",
          "rank": 5
        },
        {
          "name": "Perplexity AI",
          "toolifyUrl": "https://www.toolify.ai/tool/perplexity-ai",
          "website": "https://www.perplexity.ai/?utm_source=toolify",
          "visits": "154.9M",
          "description": "Download Comet and get Perplexity Pro for free.",
          "icon": "https://icons.duckduckgo.com/ip3/perplexity.ai.ico",
          "rank": 6
        },
        {
          "name": "OpenAI",
          "toolifyUrl": "https://www.toolify.ai/tool/openai",
          "website": "https://openai.com/?utm_source=toolify",
          "visits": "195.7M",
          "description": "AI research and deployment company focused on building safe and beneficial AGI.",
          "icon": "https://icons.duckduckgo.com/ip3/openai.com.ico",
          "rank": 7
        },
        {
          "name": "SPICYCHAT.AI",
          "toolifyUrl": "https://www.toolify.ai/tool/spicychat-ai",
          "website": "https://spicychat.ai/?ref=n2mwzdu",
          "visits": "82.0M",
          "description": "Chatbot platform with AI characters, allowing users to chat and create bots.",
          "icon": "https://icons.duckduckgo.com/ip3/spicychat.ai.ico",
          "rank": 8
        },
        {
          "name": "remove.bg",
          "toolifyUrl": "https://www.toolify.ai/tool/remove-bg",
          "website": "https://www.remove.bg/?utm_source=toolify",
          "visits": "62.7M",
          "description": "AI-powered background remover for images in 5 seconds.",
          "icon": "https://icons.duckduckgo.com/ip3/remove.bg.ico",
          "rank": 9
        },
        {
          "name": "Grammarly",
          "toolifyUrl": "https://www.toolify.ai/tool/grammarly",
          "website": "https://www.grammarly.com/?utm_source=toolify",
          "visits": "58.3M",
          "description": "AI writing assistant for grammar, style, and tone correction and improvement.",
          "icon": "https://icons.duckduckgo.com/ip3/grammarly.com.ico",
          "rank": 10
        }
      ]
    },
    {
      "key": "competitive-tracks",
      "title": "Competitive but proven tracks",
      "subtitle": "10 crowded tracks where demand has already been market-validated.",
      "kind": "tracks",
      "items": [
        {
          "name": "AI Chatbot",
          "url": "https://www.toolify.ai/category/ai-chatbot",
          "description": "General assistant and role-play chat products with massive traffic.",
          "rank": 1,
          "signals": "many active products"
        },
        {
          "name": "AI Writing Assistants",
          "url": "https://www.toolify.ai/category/ai-writing-assistants",
          "description": "Writing, paraphrasing, grammar, and content production.",
          "rank": 2,
          "signals": "clear SEO search intent"
        },
        {
          "name": "AI Image Generator",
          "url": "https://www.toolify.ai/category/ai-image-generator",
          "description": "Creative generation, avatars, ads, and product images.",
          "rank": 3,
          "signals": "multiple monetization paths"
        },
        {
          "name": "AI Video Generator",
          "url": "https://www.toolify.ai/category/ai-video-generator",
          "description": "Short video, editing, captions, and repurposing.",
          "rank": 4,
          "signals": "many active products"
        },
        {
          "name": "AI Code Assistant",
          "url": "https://www.toolify.ai/category/ai-code-assistant",
          "description": "Developer productivity, agents, debugging, and app generation.",
          "rank": 5,
          "signals": "clear SEO search intent"
        },
        {
          "name": "AI Search Engine",
          "url": "https://www.toolify.ai/category/ai-search-engine",
          "description": "Answer engines, research tools, and citation workflows.",
          "rank": 6,
          "signals": "multiple monetization paths"
        },
        {
          "name": "AI Productivity Tools",
          "url": "https://www.toolify.ai/category/ai-productivity-tools",
          "description": "Meeting, docs, workflow, automation, and office productivity.",
          "rank": 7,
          "signals": "many active products"
        },
        {
          "name": "AI Education Assistant",
          "url": "https://www.toolify.ai/category/ai-education-assistant",
          "description": "Tutoring, homework, language learning, and study workflows.",
          "rank": 8,
          "signals": "clear SEO search intent"
        },
        {
          "name": "AI Voice Assistants",
          "url": "https://www.toolify.ai/category/ai-voice-assistants",
          "description": "TTS, voice cloning, dubbing, and audio generation.",
          "rank": 9,
          "signals": "multiple monetization paths"
        },
        {
          "name": "AI Marketing Tools",
          "url": "https://www.toolify.ai/category/ai-marketing-tools",
          "description": "SEO, ads, landing pages, social content, and sales copy.",
          "rank": 10,
          "signals": "many active products"
        }
      ]
    }
  ],
  "meta": {
    "sources": {
      "topTools": "toolify",
      "highTraffic": "fallback",
      "fastGrowth": "fallback",
      "paidProducts": "toolify"
    }
  }
} as const;
