// Auto-generated by scripts/update-toolify-data.mjs
export const toolifyData = {
  "updatedAt": "2026-05-22T08:31:07.057Z",
  "source": "Toolify public ranking pages via r.jina.ai with curated fallback when blocked",
  "sections": [
    {
      "key": "top-tools",
      "title": "Top validated AI tools",
      "subtitle": "10 AI products ranking near the front of Toolify-style market lists.",
      "kind": "products",
      "items": [
        {
          "name": "ChatGPT",
          "toolifyUrl": "https://www.toolify.ai/tool/chatgpt-4",
          "website": "https://chatgpt.com/",
          "visits": "5.5B",
          "description": "A free-to-use AI system for conversations, insights, coding, and task automation.",
          "icon": "https://icons.duckduckgo.com/ip3/chatgpt.com.ico",
          "rank": 1
        },
        {
          "name": "Claude",
          "toolifyUrl": "https://www.toolify.ai/tool/claude-2",
          "website": "https://claude.ai/",
          "visits": "823.5M",
          "description": "Anthropic AI assistant for writing, analysis, coding, and knowledge work.",
          "icon": "https://icons.duckduckgo.com/ip3/claude.ai.ico",
          "rank": 2
        },
        {
          "name": "Perplexity AI",
          "toolifyUrl": "https://www.toolify.ai/tool/perplexity-ai",
          "website": "https://www.perplexity.ai/",
          "visits": "154.9M",
          "description": "AI answer engine combining search, citations, and conversational research.",
          "icon": "https://icons.duckduckgo.com/ip3/perplexity.ai.ico",
          "rank": 3
        },
        {
          "name": "Notion AI",
          "toolifyUrl": "https://www.toolify.ai/tool/notion-ai",
          "website": "https://www.notion.so/",
          "visits": "174.5M",
          "description": "All-in-one workspace with AI notes, docs, projects, and knowledge workflows.",
          "icon": "https://icons.duckduckgo.com/ip3/notion.so.ico",
          "rank": 4
        },
        {
          "name": "OpenAI",
          "toolifyUrl": "https://www.toolify.ai/tool/openai",
          "website": "https://openai.com/",
          "visits": "195.7M",
          "description": "AI research and deployment platform for models, APIs, and products.",
          "icon": "https://icons.duckduckgo.com/ip3/openai.com.ico",
          "rank": 5
        },
        {
          "name": "remove.bg",
          "toolifyUrl": "https://www.toolify.ai/tool/remove-bg",
          "website": "https://www.remove.bg/",
          "visits": "62.7M",
          "description": "AI-powered background remover for images in seconds.",
          "icon": "https://icons.duckduckgo.com/ip3/remove.bg.ico",
          "rank": 6
        },
        {
          "name": "Grammarly",
          "toolifyUrl": "https://www.toolify.ai/tool/grammarly",
          "website": "https://www.grammarly.com/",
          "visits": "58.3M",
          "description": "AI writing assistant for grammar, clarity, style, and tone.",
          "icon": "https://icons.duckduckgo.com/ip3/grammarly.com.ico",
          "rank": 7
        },
        {
          "name": "CapCut",
          "toolifyUrl": "https://www.toolify.ai/tool/capcut-com",
          "website": "https://capcut.com/",
          "visits": "51.2M",
          "description": "AI video editor and graphic design tool for creators.",
          "icon": "https://icons.duckduckgo.com/ip3/capcut.com.ico",
          "rank": 8
        },
        {
          "name": "QuillBot",
          "toolifyUrl": "https://www.toolify.ai/tool/quillbot-paraphraser",
          "website": "https://quillbot.com/",
          "visits": "48.1M",
          "description": "AI paraphrasing, grammar, citation, and writing productivity suite.",
          "icon": "https://icons.duckduckgo.com/ip3/quillbot.com.ico",
          "rank": 9
        },
        {
          "name": "ElevenLabs",
          "toolifyUrl": "https://www.toolify.ai/tool/elevenlabs-io",
          "website": "https://elevenlabs.io/",
          "visits": "33.3M",
          "description": "AI audio platform for text-to-speech, voice cloning, and dubbing.",
          "icon": "https://icons.duckduckgo.com/ip3/elevenlabs.io.ico",
          "rank": 10
        }
      ]
    },
    {
      "key": "high-traffic-categories",
      "title": "High-traffic categories",
      "subtitle": "10 categories with broad search and usage demand.",
      "kind": "categories",
      "items": [
        {
          "name": "AI Chatbot",
          "url": "https://www.toolify.ai/category/ai-chatbot",
          "description": "General assistant and role-play chat products with massive traffic.",
          "rank": 1
        },
        {
          "name": "AI Writing Assistants",
          "url": "https://www.toolify.ai/category/ai-writing-assistants",
          "description": "Writing, paraphrasing, grammar, and content production.",
          "rank": 2
        },
        {
          "name": "AI Image Generator",
          "url": "https://www.toolify.ai/category/ai-image-generator",
          "description": "Creative generation, avatars, ads, and product images.",
          "rank": 3
        },
        {
          "name": "AI Video Generator",
          "url": "https://www.toolify.ai/category/ai-video-generator",
          "description": "Short video, editing, captions, and repurposing.",
          "rank": 4
        },
        {
          "name": "AI Code Assistant",
          "url": "https://www.toolify.ai/category/ai-code-assistant",
          "description": "Developer productivity, agents, debugging, and app generation.",
          "rank": 5
        },
        {
          "name": "AI Search Engine",
          "url": "https://www.toolify.ai/category/ai-search-engine",
          "description": "Answer engines, research tools, and citation workflows.",
          "rank": 6
        },
        {
          "name": "AI Productivity Tools",
          "url": "https://www.toolify.ai/category/ai-productivity-tools",
          "description": "Meeting, docs, workflow, automation, and office productivity.",
          "rank": 7
        },
        {
          "name": "AI Education Assistant",
          "url": "https://www.toolify.ai/category/ai-education-assistant",
          "description": "Tutoring, homework, language learning, and study workflows.",
          "rank": 8
        },
        {
          "name": "AI Voice Assistants",
          "url": "https://www.toolify.ai/category/ai-voice-assistants",
          "description": "TTS, voice cloning, dubbing, and audio generation.",
          "rank": 9
        },
        {
          "name": "AI Marketing Tools",
          "url": "https://www.toolify.ai/category/ai-marketing-tools",
          "description": "SEO, ads, landing pages, social content, and sales copy.",
          "rank": 10
        }
      ]
    },
    {
      "key": "fast-growth-tools",
      "title": "Fast-growth / rising tools",
      "subtitle": "10 rising tool ideas and products worth watching.",
      "kind": "products",
      "items": [
        {
          "name": "GPT image 2 Prompt",
          "toolifyUrl": "https://www.toolify.ai/prompts/gpt-image-2",
          "website": "https://www.toolify.ai/prompts/gpt-image-2",
          "visits": "New",
          "description": "Prompt collection riding image-generation demand.",
          "icon": "https://icons.duckduckgo.com/ip3/gptimage2.com.ico",
          "rank": 1
        },
        {
          "name": "AI Humanizer",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Humanizer",
          "website": "https://www.toolify.ai/search/AI%20Humanizer",
          "visits": "Rising",
          "description": "Tools that rewrite AI text into more natural human tone.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20humanizer.com.ico",
          "rank": 2
        },
        {
          "name": "AI Detector",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Detector",
          "website": "https://www.toolify.ai/search/AI%20Detector",
          "visits": "Rising",
          "description": "Content authenticity and AI-detection utilities.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20detector.com.ico",
          "rank": 3
        },
        {
          "name": "AI Resume Builder",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Resume%20Builder",
          "website": "https://www.toolify.ai/search/AI%20Resume%20Builder",
          "visits": "Rising",
          "description": "Career tools for resumes, cover letters, and ATS optimization.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20resume20builder.com.ico",
          "rank": 4
        },
        {
          "name": "AI PPT Maker",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20PPT%20Maker",
          "website": "https://www.toolify.ai/search/AI%20PPT%20Maker",
          "visits": "Rising",
          "description": "Presentation generation tools for business and education.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20ppt20maker.com.ico",
          "rank": 5
        },
        {
          "name": "AI Headshot Generator",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Headshot%20Generator",
          "website": "https://www.toolify.ai/search/AI%20Headshot%20Generator",
          "visits": "Rising",
          "description": "Personal branding photo tools for LinkedIn and portfolios.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20headshot20generator.com.ico",
          "rank": 6
        },
        {
          "name": "AI Video Generator",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Video%20Generator",
          "website": "https://www.toolify.ai/search/AI%20Video%20Generator",
          "visits": "Rising",
          "description": "Text-to-video and social video automation products.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20video20generator.com.ico",
          "rank": 7
        },
        {
          "name": "AI Logo Generator",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Logo%20Generator",
          "website": "https://www.toolify.ai/search/AI%20Logo%20Generator",
          "visits": "Rising",
          "description": "Branding micro-tools with strong small-business intent.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20logo20generator.com.ico",
          "rank": 8
        },
        {
          "name": "AI Voice Generator",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Voice%20Generator",
          "website": "https://www.toolify.ai/search/AI%20Voice%20Generator",
          "visits": "Rising",
          "description": "Voiceover and dubbing tools for creators.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20voice20generator.com.ico",
          "rank": 9
        },
        {
          "name": "AI Coding Agent",
          "toolifyUrl": "https://www.toolify.ai/search/AI%20Coding%20Agent",
          "website": "https://www.toolify.ai/search/AI%20Coding%20Agent",
          "visits": "Rising",
          "description": "Developer automation tools for code generation and review.",
          "icon": "https://icons.duckduckgo.com/ip3/ai20coding20agent.com.ico",
          "rank": 10
        }
      ]
    },
    {
      "key": "paid-products",
      "title": "Products with payment signals",
      "subtitle": "10 products with payment-platform or subscription evidence.",
      "kind": "products",
      "items": [
        {
          "name": "ChatGPT",
          "toolifyUrl": "https://www.toolify.ai/tool/chatgpt-4",
          "website": "https://chatgpt.com/",
          "visits": "5.5B",
          "description": "A free-to-use AI system for conversations, insights, coding, and task automation.",
          "icon": "https://icons.duckduckgo.com/ip3/chatgpt.com.ico",
          "rank": 1
        },
        {
          "name": "Claude",
          "toolifyUrl": "https://www.toolify.ai/tool/claude-2",
          "website": "https://claude.ai/",
          "visits": "823.5M",
          "description": "Anthropic AI assistant for writing, analysis, coding, and knowledge work.",
          "icon": "https://icons.duckduckgo.com/ip3/claude.ai.ico",
          "rank": 2
        },
        {
          "name": "Perplexity AI",
          "toolifyUrl": "https://www.toolify.ai/tool/perplexity-ai",
          "website": "https://www.perplexity.ai/",
          "visits": "154.9M",
          "description": "AI answer engine combining search, citations, and conversational research.",
          "icon": "https://icons.duckduckgo.com/ip3/perplexity.ai.ico",
          "rank": 3
        },
        {
          "name": "Notion AI",
          "toolifyUrl": "https://www.toolify.ai/tool/notion-ai",
          "website": "https://www.notion.so/",
          "visits": "174.5M",
          "description": "All-in-one workspace with AI notes, docs, projects, and knowledge workflows.",
          "icon": "https://icons.duckduckgo.com/ip3/notion.so.ico",
          "rank": 4
        },
        {
          "name": "OpenAI",
          "toolifyUrl": "https://www.toolify.ai/tool/openai",
          "website": "https://openai.com/",
          "visits": "195.7M",
          "description": "AI research and deployment platform for models, APIs, and products.",
          "icon": "https://icons.duckduckgo.com/ip3/openai.com.ico",
          "rank": 5
        },
        {
          "name": "remove.bg",
          "toolifyUrl": "https://www.toolify.ai/tool/remove-bg",
          "website": "https://www.remove.bg/",
          "visits": "62.7M",
          "description": "AI-powered background remover for images in seconds.",
          "icon": "https://icons.duckduckgo.com/ip3/remove.bg.ico",
          "rank": 6
        },
        {
          "name": "Grammarly",
          "toolifyUrl": "https://www.toolify.ai/tool/grammarly",
          "website": "https://www.grammarly.com/",
          "visits": "58.3M",
          "description": "AI writing assistant for grammar, clarity, style, and tone.",
          "icon": "https://icons.duckduckgo.com/ip3/grammarly.com.ico",
          "rank": 7
        },
        {
          "name": "CapCut",
          "toolifyUrl": "https://www.toolify.ai/tool/capcut-com",
          "website": "https://capcut.com/",
          "visits": "51.2M",
          "description": "AI video editor and graphic design tool for creators.",
          "icon": "https://icons.duckduckgo.com/ip3/capcut.com.ico",
          "rank": 8
        },
        {
          "name": "QuillBot",
          "toolifyUrl": "https://www.toolify.ai/tool/quillbot-paraphraser",
          "website": "https://quillbot.com/",
          "visits": "48.1M",
          "description": "AI paraphrasing, grammar, citation, and writing productivity suite.",
          "icon": "https://icons.duckduckgo.com/ip3/quillbot.com.ico",
          "rank": 9
        },
        {
          "name": "ElevenLabs",
          "toolifyUrl": "https://www.toolify.ai/tool/elevenlabs-io",
          "website": "https://elevenlabs.io/",
          "visits": "33.3M",
          "description": "AI audio platform for text-to-speech, voice cloning, and dubbing.",
          "icon": "https://icons.duckduckgo.com/ip3/elevenlabs.io.ico",
          "rank": 10
        }
      ]
    },
    {
      "key": "competitive-tracks",
      "title": "Competitive but proven tracks",
      "subtitle": "10 crowded tracks where demand has already been market-validated.",
      "kind": "tracks",
      "items": [
        {
          "name": "AI Chatbot",
          "url": "https://www.toolify.ai/category/ai-chatbot",
          "description": "General assistant and role-play chat products with massive traffic.",
          "rank": 1,
          "signals": "many active products"
        },
        {
          "name": "AI Writing Assistants",
          "url": "https://www.toolify.ai/category/ai-writing-assistants",
          "description": "Writing, paraphrasing, grammar, and content production.",
          "rank": 2,
          "signals": "clear SEO search intent"
        },
        {
          "name": "AI Image Generator",
          "url": "https://www.toolify.ai/category/ai-image-generator",
          "description": "Creative generation, avatars, ads, and product images.",
          "rank": 3,
          "signals": "multiple monetization paths"
        },
        {
          "name": "AI Video Generator",
          "url": "https://www.toolify.ai/category/ai-video-generator",
          "description": "Short video, editing, captions, and repurposing.",
          "rank": 4,
          "signals": "many active products"
        },
        {
          "name": "AI Code Assistant",
          "url": "https://www.toolify.ai/category/ai-code-assistant",
          "description": "Developer productivity, agents, debugging, and app generation.",
          "rank": 5,
          "signals": "clear SEO search intent"
        },
        {
          "name": "AI Search Engine",
          "url": "https://www.toolify.ai/category/ai-search-engine",
          "description": "Answer engines, research tools, and citation workflows.",
          "rank": 6,
          "signals": "multiple monetization paths"
        },
        {
          "name": "AI Productivity Tools",
          "url": "https://www.toolify.ai/category/ai-productivity-tools",
          "description": "Meeting, docs, workflow, automation, and office productivity.",
          "rank": 7,
          "signals": "many active products"
        },
        {
          "name": "AI Education Assistant",
          "url": "https://www.toolify.ai/category/ai-education-assistant",
          "description": "Tutoring, homework, language learning, and study workflows.",
          "rank": 8,
          "signals": "clear SEO search intent"
        },
        {
          "name": "AI Voice Assistants",
          "url": "https://www.toolify.ai/category/ai-voice-assistants",
          "description": "TTS, voice cloning, dubbing, and audio generation.",
          "rank": 9,
          "signals": "multiple monetization paths"
        },
        {
          "name": "AI Marketing Tools",
          "url": "https://www.toolify.ai/category/ai-marketing-tools",
          "description": "SEO, ads, landing pages, social content, and sales copy.",
          "rank": 10,
          "signals": "many active products"
        }
      ]
    }
  ],
  "meta": {
    "sources": {
      "topTools": "fallback",
      "highTraffic": "fallback",
      "fastGrowth": "fallback",
      "paidProducts": "fallback"
    }
  }
} as const;
